name: Compile TeaVM Java 21 to GitHub Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Java 21 JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build and Transpile via TeaVM
      run: mvn clean package

    - name: Copy index.html into deploy directory
      run: cp index.html target/generated/js/

    - name: Deploy Compiled Web App to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: target/generated/js
        branch: gh-pages
